carto_routes: table_34_routes
carto_metadata: table_34_narratives_metadata

keep_files: ['assets/bundle.js']

baseurl: '/passages-to-freedom'

sass:
  style: compressed

webpack: false

collections:
  texts:
    output: true