carto_routes: table_34_reordered_data
carto_metadata: table_34_reordered_metadata

keep_files: ['assets/bundle.js']
baseurl: '/passages-to-freedom'

sass:
  style: compressed

collections:
  texts:
    output: true
